name: x86-64 Pull and Save Docker Image
on:
  workflow_dispatch:
    inputs:
      docker_images:
        description: '请填写docker镜像名称 多个用英文逗号分开'
        required: true
        default: 'alpine:latest,busybox:stable-glibc'  # 设置默认的 Docker 镜像列表

jobs:
  pull_and_package:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Clean up Docker to free space
      run: |
          docker system prune -a -f
          docker volume prune -f
          docker image prune -a
          
    - name: login aliyun docker repo
      run: |
          echo "login aliyun docker repo..."
          docker login -u 1635401918@qq.com -p pqg163@qq.com registry.cn-hangzhou.aliyuncs.com
          
    - name: Pull Docker Images
      run: |
        images="${{ github.event.inputs.docker_images }}"
          IFS=',' read -r -a image_array <<< "$images"
          for image in "${image_array[@]}"; do
            docker pull "${image}" --platform "linux/amd64"
            image_name="${image//\//_}"
            image_name="${image_name//:/_}"
            image_name="${image_name}-amd64"
            docker tag "${image}" registry.cn-hangzhou.aliyuncs.com/main-img/main-repo:"${image_name}"
            echo "pushing 【registry.cn-hangzhou.aliyuncs.com/main-img/main-repo:${image_name}】 image to aliyun"
            docker push registry.cn-hangzhou.aliyuncs.com/main-img/main-repo:"${image_name}"
            echo "push to aliyun repo success!"
          done

    - name: login out aliyun docker repo
      run: |
          docker logout registry.cn-hangzhou.aliyuncs.com
